// <auto-generated />

namespace StructId;

/// <summary>
/// Interface for struct-based identifiers.
/// </summary>
/// <typeparam name="TId">The struct type for the inner <see cref="Value"/> of the identifier.</typeparam>
public partial interface IStructId<TId> where TId : struct
{
    /// <summary>
    /// Gets the underlying value of the identifier.
    /// </summary>
    TId Value { get; }
}