// <auto-generated />

namespace StructId;

/// <summary>
/// Interface for string-based identifiers.
/// </summary>
public partial interface IStructId
{
    /// <summary>
    /// Gets the underlying value of the identifier.
    /// </summary>
    string Value { get; }
}
