// <auto-generated />

using System.CodeDom.Compiler;

namespace StructId;

/// <summary>
/// Interface for struct-based identifiers.
/// </summary>
/// <typeparam name="TValue">The struct type for the inner <see cref="Value"/> of the identifier.</typeparam>
[GeneratedCode("StructId", default)]
public partial interface IStructId<TValue> where TValue : struct
{
    /// <summary>
    /// Gets the underlying value of the identifier.
    /// </summary>
    TValue Value { get; }
}