// <auto-generated />

using System.CodeDom.Compiler;

namespace StructId;

/// <summary>
/// Interface for string-based identifiers.
/// </summary>
[GeneratedCode("StructId", default)]
public partial interface IStructId
{
    /// <summary>
    /// Gets the underlying value of the identifier.
    /// </summary>
    string Value { get; }
}
