// <auto-generated />
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructId;

readonly partial record struct TSelf : INewable<TSelf, TId>
{
    /// <summary>
    /// Provides value conversion for Entity Framework Core
    /// </summary>
    public partial class EntityFrameworkValueConverter : ValueConverter<TSelf, TId>
    {
        public EntityFrameworkValueConverter() : this(null) { }

        public EntityFrameworkValueConverter(ConverterMappingHints? mappingHints = null)
            : base(id => id.Value, value => TSelf.New(value), mappingHints) { }
    }
}
