// <auto-generated/>
#nullable enable

using System.Text.Json.Serialization;
using StructId;

[JsonConverter(typeof(StructIdConverters.SystemTextJsonConverter<TSelf, TId>))]
readonly partial record struct TSelf
{
}