// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using StructId;

[TStructId]
[JsonConverter(typeof(StructIdConverters.SystemTextJsonConverter<TSelf, TValue>))]
file partial record struct TSelf
{
}

file partial record struct TSelf : IStructId<TValue>, INewable<TSelf, TValue>
{
    public TValue Value => throw new NotImplementedException();

    public static TSelf New(TValue value) => throw new NotImplementedException();
}

file record struct TValue : IParsable<TValue>
{
    public static TValue Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TValue result) => throw new NotImplementedException();
}
