// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;
using System;
using Newtonsoft.Json;
using StructId;

[TStructId]
[JsonConverter(typeof(StructIdConverters.NewtonsoftJsonConverter<TSelf, TId>))]
file readonly partial record struct TSelf
{
}

file partial record struct TSelf : IStructId<TId>, INewable<TSelf, TId>, IParsable<TSelf>
{
    public TId Value => throw new NotImplementedException();
    public static TSelf New(TId value) => throw new NotImplementedException();
    public static TSelf Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TSelf result) => throw new NotImplementedException();
}

file record struct TId : IParsable<TId>
{
    public static TId Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TId result) => throw new NotImplementedException();
}
