// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;
using System;
using Newtonsoft.Json;
using StructId;

[TStructId]
[JsonConverter(typeof(StructIdConverters.NewtonsoftJsonConverter<TSelf>))]
file readonly partial record struct TSelf
{
}

file partial record struct TSelf : IStructId, INewable<TSelf>, IParsable<TSelf>
{
    public string Value => throw new NotImplementedException();
    public static TSelf New(string value) => throw new NotImplementedException();
    public static TSelf Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TSelf result) => throw new NotImplementedException();
}