// <auto-generated />

using StructId;

[TStructId]
file partial record struct TSelf(TId Value)
{
    public static implicit operator TId(TSelf id) => id.Value;
    public static explicit operator TSelf(TId value) => new(value);
}

file record struct TId;