// <auto-generated />
#nullable enable

using System;
using StructId;

[TStructId]
file partial record struct TSelf(IFormattable Value) : IFormattable
{
    /// <inheritdoc/>
    public readonly string ToString(string? format, IFormatProvider? formatProvider)
        => ((IFormattable)Value).ToString(format, formatProvider);
}