// <auto-generated/>
#nullable enable

using System.Text.Json.Serialization;
using StructId;

[JsonConverter(typeof(StructIdConverters.SystemTextJsonConverter<Self>))]
readonly partial record struct Self
{
}