// <auto-generated />

using StructId;

[TStructId]
file partial record struct TSelf(TValue Value) : INewable<TSelf, TValue>
{
    /// <inheritdoc/>
    public static TSelf New(TValue value) => new(value);
}

file record struct TValue;