// <auto-generated />

using System;
using StructId;

[TStructId]
file partial record struct TSelf(Guid Value)
{
    /// <summary>
    /// Creates a new instance of <typeparamref name="TSelf"/> with a <see cref="Guid.NewGuid"/>.
    /// </summary>
    public static TSelf New() => new(Guid.NewGuid());
}