// <auto-generated />

using StructId;

[TStructId]
file partial record struct TSelf(TId Value) : INewable<TSelf, TId>
{
    /// <inheritdoc/>
    public static TSelf New(TId value) => new(value);
}

file record struct TId;