// <auto-generated />

using System;

readonly partial record struct TSelf
{
    /// <summary>
    /// Creates a new instance of <typeparamref name="TSelf"/> with a <see cref="Guid.NewGuid"/>.
    /// </summary>
    public static TSelf New() => new(Guid.NewGuid());
}