// <auto-generated />

using StructId;

[TStructId]
file partial record struct TSelf(string Value) : INewable<TSelf>
{
    /// <inheritdoc/>
    public static TSelf New(string value) => new(value);
}
