// <auto-generated/>
#nullable enable

using Newtonsoft.Json;
using StructId;

[JsonConverter(typeof(StructIdConverters.NewtonsoftJsonConverter<TSelf, TValue>))]
readonly partial record struct TSelf
{
}