// <auto-generated/>
#nullable enable

using Newtonsoft.Json;
using StructId;

[JsonConverter(typeof(StructIdConverters.NewtonsoftJsonConverter<TStruct, TValue>))]
readonly partial record struct TStruct
{
}