// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;
using System;

readonly partial record struct Self : IParsable<Self>
{
    public static Self Parse(string s, IFormatProvider? provider)
        => s is null ? throw new ArgumentNullException(nameof(s)) : new(s);

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out Self result)
    {
        if (s is not null)
        {
            result = new Self(s);
            return true;
        }
        result = default;
        return false;
    }
}