// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;
using System;

readonly partial record struct Self : ISpanParsable<Self>
{
    /// <inheritdoc cref="IParsable{TSelf}"/>
    public static Self Parse(string s, IFormatProvider? provider)
        => s is null ? throw new ArgumentNullException(nameof(s)) : new(s);

    /// <inheritdoc cref="IParsable{TSelf}"/>
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out Self result)
    {
        if (s is not null)
        {
            result = new(s);
            return true;
        }
        result = default;
        return false;
    }

    /// <inheritdoc cref="ISpanParsable{TSelf}"/>
    public static Self Parse(ReadOnlySpan<char> input, global::System.IFormatProvider? provider) 
        => new(input.ToString());

    /// <inheritdoc cref="ISpanParsable{TSelf}"/>
    public static bool TryParse(ReadOnlySpan<char> input, IFormatProvider? provider, out Self result)
    {
        result = new(input.ToString());
        return true;
    }
}