// <auto-generated/>
#nullable enable

using System.Text.Json.Serialization;
using StructId;

#if NET7_0_OR_GREATER
[JsonConverter(typeof(StructIdConverters.SystemTextJsonConverter<SStruct>))]
#endif
readonly partial record struct SStruct
{
}