// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;
using System;
using StructId;

[TStructId]
file readonly partial record struct TSelf(/*!string*/ TValue Value) : ISpanParsable<TSelf>
{
    /// <inheritdoc cref="ISpanParsable{TSelf}"/>
    public static TSelf Parse(ReadOnlySpan<char> input, IFormatProvider? provider) => new(TValue.Parse(input, provider));

    /// <inheritdoc cref="ISpanParsable{TSelf}"/>
    public static bool TryParse(ReadOnlySpan<char> input, IFormatProvider? provider, out TSelf result)
    {
        if (TValue.TryParse(input, provider, out var value))
        {
            result = new TSelf(value);
            return true;
        }
        result = default;
        return false;
    }
}

// This will be removed when applying the template to each user-defined struct id.
file partial record struct TSelf
{
    public static TSelf Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TSelf result) => throw new NotImplementedException();
}

// This will be removed when applying the template to each user-defined struct id.
file struct TValue : ISpanParsable<TValue>
{
    public static TValue Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => throw new NotImplementedException();
    public static TValue Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, [MaybeNullWhen(false)] out TValue result) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TValue result) => throw new NotImplementedException();
}