// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;
using System;

readonly partial record struct SStruct : IParsable<SStruct>
{
    public static SStruct Parse(string s, IFormatProvider? provider) => new(s);
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out SStruct result)
    {
        if (s is not null)
        {
            result = new SStruct(s);
            return true;
        }
        result = default;
        return false;
    }
}