// <auto-generated/>
#nullable enable

using System.Text.Json.Serialization;
using StructId;

#if NET7_0_OR_GREATER
[JsonConverter(typeof(StructIdConverters.SystemTextJsonConverter<TStruct, TValue>))]
#endif
readonly partial record struct TStruct
{
}