// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using StructId;

[TStructId]
[TypeConverter(typeof(TSelf.StringConverter))]
file readonly partial record struct TSelf(/*!string*/ TValue Value)
{
    partial class StringConverter : TypeConverter
    {
        /// <inheritdoc />
        public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
            => sourceType == typeof(string) || sourceType == typeof(TSelf);

        /// <inheritdoc />
        public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        {
            if (value == null)
                return default(TSelf);

            if (value is string typedValue)
                return TSelf.New(TValue.Parse(typedValue, culture));

            throw new ArgumentException($"Cannot convert '{value}' to {nameof(TSelf)}", nameof(value));
        }

        /// <inheritdoc />
        public override bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType) 
            => destinationType == typeof(string) || destinationType == typeof(TSelf);

        /// <inheritdoc />
        public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
        {
            if (value != null)
            {
                if (destinationType == typeof(string))
                    return ((TSelf)value).Value.ToString(null, culture);

                if (destinationType == typeof(TSelf))
                    return value;
            }

            throw new InvalidOperationException($"Cannot convert '{value}' to '{destinationType}'");
        }
    }
}

file partial record struct TSelf : INewable<TSelf, TValue>
{
    public static TSelf New(TValue value) => throw new NotImplementedException();
}

// This will be removed when applying the template to each user-defined struct id.
file struct TValue : IParsable<TValue>, IFormattable
{
    public static TValue Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TValue result) => throw new NotImplementedException();
    public string ToString(string? format, IFormatProvider? formatProvider) => throw new NotImplementedException();
}