// <auto-generated />
#nullable enable

using System;
using StructId;

[TStructId]
file partial record struct Utf8SpanFormattable(IUtf8SpanFormattable Value) : IUtf8SpanFormattable
{
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider) 
        => Value.TryFormat(utf8Destination, out bytesWritten, format, provider);
}